#print "Hello World"
print "Hello Again"
print "I like typing this"
print "This is fun."
print "Yay! Printing."
print "I'd much rather you 'not'."
print 'I "said" do not touch this'
print "This will be another line you asked"
print "I added that line in Windows"
print "This line was added lastly"
print "This is new line which I added last"
